config/routes.rb
RestaurantReviews::Application.routes.draw do

  resources :restaurants do
    resources :reviews
  end

  root :to => 'restaurants#index'

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  attr_accessible :cuisine

  belongs_to :restaurant 
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address, :name, :phone_number

  has_many :reviews
  has_many :cuisines

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :review, :visit_date

  belongs_to :restaurant 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

 def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      flash[:success] = "Added a new Restaurant"
      redirect_to @restaurant
    else
      render :new
    end
  end

   def edit
    @restaurant = Restaurant.find(params[:id])
    render :edit
  end

   def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update_attributes(params[:restaurant])
    
    if @restaurant.save
      flash[:success] = "Updated Restaurant"
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find_by_id(params[:id])
    @reviews = Review.where("restaurant_id = ?", params[:id])
    if @restaurant.nil?
      @restaurant = Restaurant.all
      render :index
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.find_all_by_restaurant_id(params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(params[:review])
    if @review.save
      flash[:success] = "Added a new Review"
      redirect_to restaurant_review_path(@restaurant, @review)
    else
      render :show
    end
  end

  def edit
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    @review.update_attributes(params[:restaurant])

    if @review.save
      flash[:success] = "Updated Restaurant"
      redirect_to @review
    else
      render :edit
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
    redirect_to :index unless @review
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant Reviews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Hungry?</h1>
<p>Find somewhere to eat below</p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Location</th>
			<th>Phone Number</th>
		</tr>
	</thead>

	<tbody>
		<% unless @restaurants.empty? %>
		<% @restaurants.each do |restaurant| %>
		<tr>
			<td><%= link_to(restaurant.name, restaurant_path(restaurant)) %></td>
			<td><%= restaurant.address %></td>
			<td><%= restaurant.phone_number %></td>
		</tr>
			<% end %>
			<% else %>
			<td>"No Restaurants yet"</td>
		<% end %>
		</tbody>
		

		<td><h4><a href= "/restaurants/new/" class= "btn btn-primary" >Add a restaurant</a></h4><td>
		<td><h4><a href="/reviews/" class="btn btn-primary">Actually I want to review a restaurant</a></h4><td>

	</tbody>
</table>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>

<section class='add-restaurant'>
<div class="restaurant-form">
  <%= form_for(@restaurant) do |r| %>
		<%= r.label :name %>
		<%= r.text_field :name %>

		<%= r.label :address %>
		<%= r.text_field :address %>

		<%= r.label :phone_number %>
		<%= r.text_field :phone_number %>

	<%= r.submit "Add new Restaurant", class: "btn btn-large btn-primary" %> 

	<% end %>

	<h4><a href="/restaurants/" class="btn btn-primary">Actually I want to eat not add a restaurant</a></h4>


</div>
</section>

app/views/restaurants/show.html.erb
<h1> 
  <%= @restaurant.name %>  
</h1>

<p>
	<%= @restaurant.address %>
</p>
<p>
	<%= @restaurant.phone_number %>
</p>

	<tbody>
		<% @reviews.each do |review| %>
		<tr>
			<td><%= review.review %></td>
			<td><%= review.visit_date %></td>
		</tr>
		<% end %>
	</tbody>

<%= link_to("Add Review", new_restaurant_review_path(@restaurant)) %>

<td><h4><a href= "/restaurants/" class= "btn btn-primary" >Back to all restaurants</a></h4><td>

app/views/reviews/index.html.erb
<h1>Still Hungry?</h1>
<p>What did you think of your food</p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Review</th>
			<th>Visit Date</th>
		</tr>
	</thead>

	<tbody>
		<% unless @reviews.empty? %>
		<% @reviews.each do |review| %>
		<tr>
			<td><%= review.review %></td>
			<td><%= review.visit_date %></td>
		</tr>
			<% end %>
			<% else %>
			<td>"No Reviews yet"</td>
		<% end %>
		</tbody>

		<td><h4><a href= "/reviews/new/" class= "btn btn-primary" >Add a review</a></h4><td>

	</tbody>
</table>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>

<section class='add-restaurant'>
<div class="restaurant-form">
  <%= form_for([@restaurant, @review]) do |r| %>
		<%= r.label :review %>
		<%= r.text_field :review %>

		<%= r.label :visit_date%>
		<%= r.text_field :visit_date %>

	<%= r.submit "Add a review", class: "btn btn-large btn-primary" %> 

	<% end %>

	<h4><a href= "/restaurants/" class= "btn btn-primary" >Actually I want to eat not review a restaurant</a></h4>

</div>

app/views/reviews/show.html.erb
<h1> 
  <%= @review %>  
</h1>

<p>
	<%= @review.review %>
</p>
<p>
	<%= @review.visit_date %>
</p>

<td><h4><a href= "/restaurants/" class= "btn btn-primary" >Back to all restaurants</a></h4><td>